'use strict'

const { contextBridge, ipcRenderer } = require('electron')

contextBridge.exposeInMainWorld('dshDesktop', {
  onLog: (cb) => ipcRenderer.on('setup-log', (_e, msg) => cb(msg)),
  onStatus: (cb) => ipcRenderer.on('setup-status', (_e, msg) => cb(msg)),
  onStep: (cb) => ipcRenderer.on('setup-step', (_e, step) => cb(step)),
  onProgress: (cb) => ipcRenderer.on('setup-progress', (_e, pct) => cb(pct)),
  onUpdateEvent: (cb) => ipcRenderer.on('update-event', (_e, payload) => cb(payload)),
  appVersion: () => ipcRenderer.invoke('app-version'),
  getSettings: () => ipcRenderer.invoke('get-settings'),
  setSettings: (settings) => ipcRenderer.invoke('set-settings', settings),
  manualUpdate: () => ipcRenderer.invoke('manual-update'),
  openDataDir: () => ipcRenderer.invoke('open-data-dir'),
  openLogs: () => ipcRenderer.invoke('open-logs'),
  restartService: () => ipcRenderer.invoke('restart-service'),
  runDoctor: () => ipcRenderer.invoke('run-doctor'),
  backupData: () => ipcRenderer.invoke('backup-data'),
  restoreData: () => ipcRenderer.invoke('restore-data'),
  rollbackDsh: () => ipcRenderer.invoke('rollback-dsh'),
  getLogs: () => ipcRenderer.invoke('get-logs'),
  exportLogs: () => ipcRenderer.invoke('export-logs'),
  onAppLog: (cb) => ipcRenderer.on('app-log', (_e, line) => cb(line)),
  inboxList: () => ipcRenderer.invoke('inbox-list'),
  inboxRun: (prompt) => ipcRenderer.invoke('inbox-run', prompt),
  inboxCancel: (id) => ipcRenderer.invoke('inbox-cancel', id),
  inboxDelete: (id) => ipcRenderer.invoke('inbox-delete', id),
  inboxClear: () => ipcRenderer.invoke('inbox-clear'),
  scheduleSave: (schedule) => ipcRenderer.invoke('schedule-save', schedule),
  scheduleDelete: (id) => ipcRenderer.invoke('schedule-delete', id),
  quickSubmit: (prompt) => ipcRenderer.invoke('quick-submit', prompt),
  quickHide: () => ipcRenderer.invoke('quick-hide'),
  onInboxChanged: (cb) => ipcRenderer.on('inbox-changed', () => cb()),
})
